// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-ZunHEA0c0j2wj6ifD3c-CcUgmlIdV4',
    appId: '1:704766267174:web:2e4aedfd42733e45affbe7',
    messagingSenderId: '704766267174',
    projectId: 'hotel-management-3e42b',
    authDomain: 'hotel-management-3e42b.firebaseapp.com',
    storageBucket: 'hotel-management-3e42b.appspot.com',
    measurementId: 'G-262KNK7V2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_-BxCcKUasxccTUPrcW-T28KZRkhz00A',
    appId: '1:704766267174:android:5105a1cc6e9d49d1affbe7',
    messagingSenderId: '704766267174',
    projectId: 'hotel-management-3e42b',
    storageBucket: 'hotel-management-3e42b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb-HOeh1JPmo_VnEmNwDVzuftO3XJ-4Ac',
    appId: '1:704766267174:ios:b7de5861b02912d9affbe7',
    messagingSenderId: '704766267174',
    projectId: 'hotel-management-3e42b',
    storageBucket: 'hotel-management-3e42b.appspot.com',
    iosBundleId: 'com.kingrittik.hotelManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb-HOeh1JPmo_VnEmNwDVzuftO3XJ-4Ac',
    appId: '1:704766267174:ios:b7de5861b02912d9affbe7',
    messagingSenderId: '704766267174',
    projectId: 'hotel-management-3e42b',
    storageBucket: 'hotel-management-3e42b.appspot.com',
    iosBundleId: 'com.kingrittik.hotelManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa-ZunHEA0c0j2wj6ifD3c-CcUgmlIdV4',
    appId: '1:704766267174:web:24daab16d09cc659affbe7',
    messagingSenderId: '704766267174',
    projectId: 'hotel-management-3e42b',
    authDomain: 'hotel-management-3e42b.firebaseapp.com',
    storageBucket: 'hotel-management-3e42b.appspot.com',
    measurementId: 'G-M7FMHE9RCJ',
  );
}
